language: objective-c

install:
  - curl -L -o sketchtool-latest.zip http://sketchtool.bohemiancoding.com/sketchtool-latest.zip
  - unzip sketchtool-latest.zip
  - sh -x sketchtool/install.sh
  - rm -rf sketchtool

script:
  - mkdir out
  - script/export-png.sh out
  